"""
Ghost Fill Resynchronization Engine (GFRE)
==========================================
Standalone module that sanitizes Sierra Chart binary log fill streams by
identifying and removing ghost fills (execution records generated by SC's
internal Trade Evaluator that lack C++ strategy attribution tags), then
rebuilds an accurate, strategy-aligned, FIFO-paired trade sequence.

Architecture
------------
Stage 1 -- Tag-Validation Filter        : classify_fill()
Stage 2 -- Adaptive Bypass Detection    : _compute_note_rate()
Stage 3 -- Per-Batch Deduplication      : _dedup_fills()
Stage 4 -- FIFO Position Resynchronizer : pair_fills_to_trades()
Stage 5 -- Sequence Integrity Verifier  : verify_sequence()

Classifier Design Note (v2 — 2026-07-28)
-----------------------------------------
Rule 3 (Trading Evaluator fills) now exempts CLOSE-flagged fills from the
ghost test.  Evidence from empirical binary-log analysis of IPS_TM_7 NQ
(Jun-23 and Jul-02 2026) established that SC's Trade Evaluator processes
limit-target and stop-loss exits WITHOUT copying the C++ strategy's Order
Note (Tag 0x82) to the generated fill record.  These are therefore
legitimate exits that happen to have an empty note — NOT ghost fills.
Dropping them (the v1 behaviour) produced a $10–35k single-fill cascade
swing by leaving the FIFO queue inflated, causing all downstream sells to
pair against wrong LONG legs.  Real ghost fills are always OPEN fills
(they inject unintended new position changes); a fill SC itself marks
as CLOSE is by definition reducing an existing position and cannot be a
phantom injection.

Quick Usage
-----------
    from trading_platform.services.ghost_fill_engine import GhostFillEngine, resync

    # One-call convenience
    from trading_platform.services.binary_log_parser import _parse_file_nitro
    raw, _ = _parse_file_nitro("dataset/TradeActivityLog_2026-06-10_UTC.TM_7.data")
    result = resync(raw)
    print(result.summary())
    for trade in result.trades:
        print(trade)
"""
from __future__ import annotations

import re
import datetime
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Tuple, Any
from zoneinfo import ZoneInfo

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
NY_TZ = ZoneInfo("America/New_York")

SESSION_CLOSE_HOUR_NY        = 17
EOD_WINDOW_OPEN_MIN          = (16, 55)
EOD_WINDOW_CLOSE_MIN         = (17, 5)
ADAPTIVE_NOTE_RATE_THRESHOLD = 0.25
ADAPTIVE_MIN_FILLS           = 5
STRATEGY_TAG_PATTERNS        = ("autotrader_", "at_", "text: tag:")
EVALUATOR_FILL_SIGNATURE     = "trading evaluator"

# ---------------------------------------------------------------------------
# Plausibility bounds (FIX v3 — August 2026)
# ---------------------------------------------------------------------------
# MAX_SANE_QUANTITY: justified by inspecting 2,781,631 clean_trades across the
# full 49GB dataset.  Distribution: qty=1 (42.3%), qty=2 (18.5%), qty=3 (39.2%),
# qty=4..15 (<0.1% combined, max observed = 15).  A cap of 50 gives 3x headroom
# above the observed max before rejecting corrupted binary reads where a price
# or timestamp field is misread as a quantity.
MAX_SANE_QUANTITY = 50

# rejected_fills is a module-level audit list.  Call clear_rejected_fills() at
# the start of each batch run.  Each entry is a dict with keys:
#   account, trade_date, timestamp, symbol, field, actual_value, bound, reason
# This list is intentionally NOT thread-safe — callers must use a lock or
# collect per-thread lists and merge, as ghost_fill_cleaner.py already does.
rejected_fills: List[Dict] = []


def clear_rejected_fills() -> None:
    """Reset the module-level rejected_fills audit list for a new batch run."""
    global rejected_fills
    rejected_fills = []


def get_rejected_fills() -> List[Dict]:
    """Return a copy of the current rejected_fills audit list."""
    return list(rejected_fills)


def _record_rejected(
    fill    : "FillRecord",
    field   : str,
    actual  : float,
    bound   : float,
    reason  : str,
) -> None:
    """
    Record a fill that failed a plausibility bound check.
    Appends to the module-level rejected_fills list.
    """
    rejected_fills.append({
        "account"     : fill.account,
        "trade_date"  : fill.timestamp[:10] if fill.timestamp else "",
        "timestamp"   : fill.timestamp,
        "symbol"      : fill.symbol,
        "base_symbol" : fill.base_symbol,
        "side"        : fill.side,
        "price"       : fill.price,
        "quantity"    : fill.quantity,
        "field"       : field,
        "actual_value": actual,
        "bound"       : bound,
        "reason"      : reason,
    })
    logger.warning(
        "FILL REJECTED [%s] acct=%s sym=%s ts=%s %s=%s bound=%s",
        reason, fill.account, fill.symbol, fill.timestamp,
        field, actual, bound,
    )

SYMBOL_METADATA: Dict[str, Dict] = {
    # Full-size equity index futures
    "ES":   {"multiplier": 50,    "price_min": 500,    "price_max": 10_000},
    "NQ":   {"multiplier": 20,    "price_min": 1_000,  "price_max": 50_000},
    "YM":   {"multiplier": 5,     "price_min": 5_000,  "price_max": 100_000},
    "RTY":  {"multiplier": 50,    "price_min": 200,    "price_max": 5_000},
    "FDAX": {"multiplier": 25,    "price_min": 1_000,  "price_max": 50_000},
    # Micro equity index futures (same price range as full-size, smaller multiplier)
    "MES":  {"multiplier": 5,     "price_min": 500,    "price_max": 10_000},
    "MNQ":  {"multiplier": 2,     "price_min": 1_000,  "price_max": 50_000},
    "MYM":  {"multiplier": 0.5,   "price_min": 5_000,  "price_max": 100_000},
    "M2K":  {"multiplier": 5,     "price_min": 200,    "price_max": 5_000},
    # Energy futures
    "CL":   {"multiplier": 1_000, "price_min": 20,     "price_max": 200},
    "MCL":  {"multiplier": 100,   "price_min": 20,     "price_max": 200},
    # Metals
    "GC":   {"multiplier": 100,   "price_min": 500,    "price_max": 5_000},
    "SI":   {"multiplier": 5_000, "price_min": 10,     "price_max": 100},
    # Treasury bond futures (32nds-based prices, 90–140 typical)
    "ZB":   {"multiplier": 1_000, "price_min": 50,     "price_max": 200},
    "ZN":   {"multiplier": 1_000, "price_min": 50,     "price_max": 200},
    "ZF":   {"multiplier": 1_000, "price_min": 50,     "price_max": 200},
    "ZT":   {"multiplier": 2_000, "price_min": 90,     "price_max": 120},
}

# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class FillRecord:
    """Single execution fill extracted from a Sierra Chart binary log."""
    timestamp      : str            = ""
    ts_val         : float          = 0.0
    account        : str            = ""
    symbol         : str            = ""
    base_symbol    : str            = ""
    side           : str            = ""
    price          : float          = 0.0
    quantity       : int            = 1
    note           : str            = ""
    msgtxt         : str            = ""
    open_close     : str            = ""
    position_after : Optional[int]  = None
    order_id       : str            = ""
    position_order : int            = 999_999
    suggests_ghost : bool           = False

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "FillRecord":
        """Construct a FillRecord from a raw parser dict."""
        raw_sym = d.get("symbol", "")
        return cls(
            timestamp      = d.get("timestamp", ""),
            ts_val         = float(d.get("ts_val") or 0.0),
            account        = d.get("account_name", d.get("account", "")),
            symbol         = raw_sym,
            base_symbol    = _base_symbol(raw_sym),
            side           = d.get("side", ""),
            price          = float(d.get("price") or 0.0),
            quantity       = int(d.get("quantity") or 1),
            note           = d.get("note", ""),
            msgtxt         = d.get("msgtxt", ""),
            open_close     = d.get("open_close", ""),
            position_after = d.get("position_after"),
            order_id       = str(d.get("order_id") or d.get("internal_order_id") or ""),
            position_order = int(d.get("_position_order") or 999_999),
            suggests_ghost = bool(d.get("suggests_ghost", False)),
        )

    def is_valid(self) -> bool:
        """
        Returns True if fill passes all minimum-field and plausibility checks.

        Checks (FIX v3 — August 2026):
        1. side must be BUY or SELL
        2. price must be > 0
        3. quantity must be in (0, MAX_SANE_QUANTITY]
        4. If base_symbol is in SYMBOL_METADATA, price must be within
           [price_min, price_max] for that symbol.
        5. If base_symbol is NOT in SYMBOL_METADATA, the fill is accepted
           but recorded in rejected_fills with reason='UNKNOWN_SYMBOL' so
           unrecognised symbols are visible and reviewable.

        Rejected fills are recorded via _record_rejected() for audit.
        Callers that skip invalid fills MUST NOT silently discard them —
        the _record_rejected() call here ensures they appear in the audit.
        """
        if self.side not in ("BUY", "SELL"):
            return False
        if self.price <= 0:
            return False
        # Quantity cap
        if self.quantity <= 0:
            return False
        if self.quantity > MAX_SANE_QUANTITY:
            _record_rejected(self, "quantity", self.quantity, MAX_SANE_QUANTITY,
                             "QUANTITY_EXCEEDS_MAX")
            return False
        # Price bounds from SYMBOL_METADATA
        meta = SYMBOL_METADATA.get(self.base_symbol)
        if meta is not None:
            p_min = meta.get("price_min", 0)
            p_max = meta.get("price_max", float("inf"))
            if self.price < p_min:
                _record_rejected(self, "price", self.price, p_min,
                                 "PRICE_BELOW_MIN")
                return False
            if self.price > p_max:
                _record_rejected(self, "price", self.price, p_max,
                                 "PRICE_ABOVE_MAX")
                return False
        else:
            # Unknown symbol — accept but log so it is reviewable
            if self.base_symbol:
                rejected_fills.append({
                    "account"     : self.account,
                    "trade_date"  : self.timestamp[:10] if self.timestamp else "",
                    "timestamp"   : self.timestamp,
                    "symbol"      : self.symbol,
                    "base_symbol" : self.base_symbol,
                    "side"        : self.side,
                    "price"       : self.price,
                    "quantity"    : self.quantity,
                    "field"       : "base_symbol",
                    "actual_value": self.base_symbol,
                    "bound"       : "NOT_IN_SYMBOL_METADATA",
                    "reason"      : "UNKNOWN_SYMBOL",
                })
        return True


@dataclass
class RoundTrip:
    """Completed entry-to-exit round-trip trade from the FIFO Resynchronizer."""
    account      : str   = ""
    symbol       : str   = ""
    base_symbol  : str   = ""
    direction    : str   = ""
    quantity     : int   = 1
    entry_time   : str   = ""
    exit_time    : str   = ""
    entry_price  : float = 0.0
    exit_price   : float = 0.0
    pnl_points   : float = 0.0
    pnl_dollars  : float = 0.0
    duration_min : float = 0.0
    entry_note   : str   = ""
    exit_note    : str   = ""

    def __repr__(self) -> str:
        sign = "+" if self.pnl_dollars >= 0 else ""
        return (f"RoundTrip({self.direction} {self.quantity}x {self.symbol} | "
                f"{self.entry_time[:16]} -> {self.exit_time[:16]} | "
                f"{sign}${self.pnl_dollars:.2f})")

    def as_dict(self) -> Dict:
        """Return JSON-safe dict representation."""
        return {
            "direction":    self.direction,
            "quantity":     self.quantity,
            "symbol":       self.symbol,
            "base_symbol":  self.base_symbol,
            "entry_time":   self.entry_time,
            "exit_time":    self.exit_time,
            "entry_price":  self.entry_price,
            "exit_price":   self.exit_price,
            "pnl_points":   round(self.pnl_points, 4),
            "pnl_dollars":  round(self.pnl_dollars, 2),
            "duration_min": round(self.duration_min, 1),
        }


@dataclass
class SymbolGFREResult:
    """
    Per-symbol GFRE processing result (FIX v3 — August 2026).

    Produced by GhostFillEngine.process() for every distinct base_symbol
    found in the fill stream.  Each symbol's fills are processed through
    all 5 GFRE stages with a completely independent position counter and
    FIFO queue — cross-symbol contamination is structurally impossible.
    """
    base_symbol         : str              = ""
    total_fills         : int              = 0
    ghost_fills_dropped : int              = 0
    clean_fills         : int              = 0
    trades              : List[RoundTrip]  = field(default_factory=list)
    unpaired_fills      : List[FillRecord] = field(default_factory=list)
    direction_flips     : int              = 0
    bypass_mode         : bool             = False
    note_rate           : float            = 0.0
    integrity_ok        : bool             = True
    integrity_notes     : List[str]        = field(default_factory=list)

    def net_pnl(self) -> float:
        return sum(t.pnl_dollars for t in self.trades)

    def as_dict(self) -> Dict:
        """JSON-safe dict for per-symbol audit records."""
        net = self.net_pnl()
        return {
            "base_symbol":          self.base_symbol,
            "total_fills":          self.total_fills,
            "ghost_fills_dropped":  self.ghost_fills_dropped,
            "clean_fills":          self.clean_fills,
            "total_trades":         len(self.trades),
            "net_pnl_dollars":      round(net, 2),
            "direction_flips":      self.direction_flips,
            "bypass_mode":          self.bypass_mode,
            "note_rate":            round(self.note_rate, 4),
            "integrity_ok":         self.integrity_ok,
            "integrity_notes":      self.integrity_notes,
            "unpaired_fills":       len(self.unpaired_fills),
        }


@dataclass
class GFREResult:
    """Complete output of a GFRE processing run."""
    total_raw_fills     : int                          = 0
    ghost_fills_dropped : int                          = 0
    clean_fills         : int                          = 0
    trades              : List[RoundTrip]              = field(default_factory=list)
    unpaired_fills      : List[FillRecord]             = field(default_factory=list)
    direction_flips     : int                          = 0
    bypass_mode         : bool                         = False
    integrity_ok        : bool                         = True
    notes               : List[str]                    = field(default_factory=list)
    # FIX v3: per-symbol breakdown — each entry is an independent result
    per_symbol          : Dict[str, SymbolGFREResult]  = field(default_factory=dict)

    def summary(self) -> str:
        """One-line human-readable summary of the run."""
        wins   = sum(1 for t in self.trades if t.pnl_dollars > 0)
        losses = len(self.trades) - wins
        net    = sum(t.pnl_dollars for t in self.trades)
        sign   = "+" if net >= 0 else ""
        syms   = ", ".join(sorted(self.per_symbol.keys())) if self.per_symbol else "?"
        return (
            f"GFRE | Symbols: [{syms}] | Raw: {self.total_raw_fills} | "
            f"Ghost dropped: {self.ghost_fills_dropped} | "
            f"Clean: {self.clean_fills} | "
            f"Trades: {len(self.trades)} ({wins}W/{losses}L) | "
            f"Net: {sign}${net:,.2f} | "
            f"Flips: {self.direction_flips} | "
            f"Integrity: {'PASS' if self.integrity_ok else 'FAIL'}"
        )

    def as_dict(self) -> Dict:
        """JSON-safe dict for API responses."""
        wins = sum(1 for t in self.trades if t.pnl_dollars > 0)
        net  = sum(t.pnl_dollars for t in self.trades)
        return {
            "total_raw_fills":      self.total_raw_fills,
            "ghost_fills_dropped":  self.ghost_fills_dropped,
            "clean_fills":          self.clean_fills,
            "total_trades":         len(self.trades),
            "winning_trades":       wins,
            "losing_trades":        len(self.trades) - wins,
            "net_pnl_dollars":      round(net, 2),
            "direction_flips":      self.direction_flips,
            "bypass_mode":          self.bypass_mode,
            "integrity_ok":         self.integrity_ok,
            "unpaired_fills":       len(self.unpaired_fills),
            "notes":                self.notes,
            "trades":               [t.as_dict() for t in self.trades],
            "per_symbol":           {k: v.as_dict() for k, v in self.per_symbol.items()},
        }


# ---------------------------------------------------------------------------
# Internal Helpers
# ---------------------------------------------------------------------------

def _base_symbol(raw: str) -> str:
    """Normalize a Sierra Chart raw symbol to its base instrument code."""
    s = raw.upper()
    overrides = {
        # Crude oil
        "CLN": "CL", "CLH": "CL", "CLQ": "CL", "CLU": "CL", "CLV": "CL", "CLZ": "CL",
        # Micro crude
        "MCL": "MCL",
        # S&P 500
        "ESM": "ES", "ESU": "ES", "ESZ": "ES", "ESH": "ES",
        # Micro S&P
        "MES": "MES",
        # Nasdaq-100
        "NQM": "NQ", "NQU": "NQ", "NQZ": "NQ", "NQH": "NQ",
        # Micro Nasdaq
        "MNQ": "MNQ",
        # Dow Jones
        "YMM": "YM", "YMU": "YM", "YMZ": "YM", "YMH": "YM",
        # Micro Dow
        "MYM": "MYM",
        # Russell 2000
        "RTY": "RTY", "RTYM": "RTY", "RTYU": "RTY", "RTYZ": "RTY", "RTYH": "RTY",
        # Micro Russell
        "M2K": "M2K", "M2KM": "M2K", "M2KU": "M2K", "M2KZ": "M2K", "M2KH": "M2K",
        # DAX
        "FDAX": "FDAX", "FDXM": "FDAX",
        # Gold
        "GCM": "GC", "GCZ": "GC", "GCQ": "GC", "GCJ": "GC", "GCV": "GC", "GCG": "GC",
        # Silver
        "SIK": "SI", "SIN": "SI", "SIU": "SI", "SIZ": "SI", "SIH": "SI",
        # Treasury bonds (ZB=30yr, ZN=10yr, ZF=5yr, ZT=2yr)
        "ZBM": "ZB", "ZBU": "ZB", "ZBZ": "ZB", "ZBH": "ZB",
        "ZNM": "ZN", "ZNU": "ZN", "ZNZ": "ZN", "ZNH": "ZN",
        "ZFM": "ZF", "ZFU": "ZF", "ZFZ": "ZF", "ZFH": "ZF",
        "ZTM": "ZT", "ZTU": "ZT", "ZTZ": "ZT", "ZTH": "ZT",
    }
    m = re.search(r"([A-Z]+)", s)
    if not m:
        return s
    head = m.group(1)
    if head[:3] in overrides:
        return overrides[head[:3]]
    for sym in sorted(SYMBOL_METADATA.keys(), key=len, reverse=True):
        if head.startswith(sym):
            return sym
    return head


def _multiplier(base_symbol: str) -> float:
    """Return the dollar-per-point contract multiplier for a base symbol."""
    return float(SYMBOL_METADATA.get(base_symbol, {}).get("multiplier", 1))


def _to_ny(ts_str: str) -> Optional[datetime.datetime]:
    """Parse ISO 8601 UTC string -> New York aware datetime. None on failure."""
    if not ts_str:
        return None
    try:
        dt = datetime.datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=datetime.timezone.utc)
        return dt.astimezone(NY_TZ)
    except Exception:
        return None


def _is_eod_exempt(ts_str: str) -> bool:
    """
    Return True if fill is in the EOD exempt window (16:55-17:05 NY).
    Session flatten events at day rollover often lack strategy tags.
    """
    ny = _to_ny(ts_str)
    if not ny:
        return False
    h, mn = ny.hour, ny.minute
    if h == EOD_WINDOW_OPEN_MIN[0] and mn >= EOD_WINDOW_OPEN_MIN[1]:
        return True
    if h == EOD_WINDOW_CLOSE_MIN[0] and mn <= EOD_WINDOW_CLOSE_MIN[1]:
        return True
    return False


def _has_strategy_tag(note: str, msgtxt: str) -> bool:
    """
    Return True if note (Tag 0x82) or message text contains a valid
    strategy attribution token.
    """
    if re.search(r"[A-Za-z0-9]", (note or "").strip()):
        return True
    ml = (msgtxt or "").lower()
    return any(p in ml for p in STRATEGY_TAG_PATTERNS)


# ---------------------------------------------------------------------------
# Stage 1: Tag-Validation Filter
# ---------------------------------------------------------------------------

def classify_fill(fill: FillRecord) -> bool:
    """
    Stage 1 -- Tag-Validation Filter.

    Returns True if the fill is a ghost (should be dropped).

    Rules
    -----
    1. qty==1: Always retain (1-lot exemption -- single-contract fills
       are almost always legitimate stop-outs or 1-lot strategy entries).
    2. EOD window (16:55-17:05 NY): Always retain (session flattenings
       often lack tags).
    3. Trading Evaluator signature in message:
       - CLOSE flag: Always retain.  SC's Trade Evaluator processes
         limit-target and stop-loss exits WITHOUT propagating the
         strategy's Tag 0x82 note.  These are real exits, not ghosts.
         Empirical evidence: both large cascade swings (Jun-23 -$10,620
         and Jul-02 -$35,835) were caused by dropping CLOSE TE fills.
       - OPEN flag with no strategy tag: ghost.
       - OPEN/unknown with strategy tag: retain.
    4. Non-Evaluator fills:
       - CLOSE (exit): Always retain.
       - OPEN/unknown with no tag: ghost.
    """
    if fill.quantity == 1:
        return False
    if _is_eod_exempt(fill.timestamp):
        return False

    msg_l        = fill.msgtxt.lower()
    is_evaluator = EVALUATOR_FILL_SIGNATURE in msg_l

    if is_evaluator:
        # FIX v2: CLOSE exits from TE are real exits — always retain.
        # Only OPEN TE fills that lack a strategy tag are ghosts.
        if fill.open_close == "CLOSE":
            return False
        return not _has_strategy_tag(fill.note, fill.msgtxt)

    if fill.open_close == "CLOSE":
        return False
    return not _has_strategy_tag(fill.note, fill.msgtxt)


# ---------------------------------------------------------------------------
# Stage 2: Adaptive Bypass Detection
# ---------------------------------------------------------------------------

def _compute_note_rate(fills: List[FillRecord]) -> Tuple[float, bool]:
    """
    Stage 2 -- Adaptive Bypass Detection.

    Compute note coverage rate. If <25% of fills have strategy notes
    and there are >5 fills total, activate bypass mode (no-note account).

    Returns (note_rate, bypass_active).
    """
    total = len(fills)
    if total == 0:
        return 1.0, False
    with_notes = sum(1 for f in fills if f.note.strip())
    rate   = with_notes / total
    bypass = rate < ADAPTIVE_NOTE_RATE_THRESHOLD and total > ADAPTIVE_MIN_FILLS
    return rate, bypass


# ---------------------------------------------------------------------------
# Stage 3: Per-Batch Deduplication
# ---------------------------------------------------------------------------

def _dedup_fills(fills: List[FillRecord], bucket_ms: int = 250) -> List[FillRecord]:
    """
    Stage 3 -- Per-Batch Deduplication.

    Sierra Chart may emit the same fill record within ~460ms. Collapse
    duplicates using a composite time-bucket key. The richer record
    (one with a strategy note, or one NOT flagged as ghost) is kept.

    Parameters
    ----------
    fills     : Fills sorted by ts_val ascending.
    bucket_ms : Bucket width in milliseconds (default 250ms).
    """
    bucket_sec = bucket_ms / 1000.0
    seen: Dict[tuple, FillRecord] = {}
    for f in fills:
        ts_bucket = round(f.ts_val / bucket_sec) * bucket_sec
        key = (ts_bucket, f.price, f.side, f.quantity, f.account, f.order_id)
        if key not in seen:
            seen[key] = f
        else:
            ex = seen[key]
            if not ex.note.strip() and f.note.strip():
                seen[key] = f
            elif ex.suggests_ghost and not f.suggests_ghost:
                seen[key] = f
    return list(seen.values())


# ---------------------------------------------------------------------------
# Stage 4: FIFO Position Resynchronizer
# ---------------------------------------------------------------------------

@dataclass
class _OpenLeg:
    """An unpaired entry fill held in the FIFO pairing queue."""
    fill     : FillRecord
    side     : str
    qty      : int
    price    : float
    time_str : str


def _make_round_trip(entry: _OpenLeg, exit_fill: FillRecord) -> RoundTrip:
    """
    Compute PnL and build a RoundTrip from an open leg and an exit fill.

    FIX v3 (August 2026): Since pair_fills_to_trades() is now called once
    per base_symbol group, entry and exit are GUARANTEED to be from the
    same instrument.  The previous fallback 'exit_fill.symbol or
    entry.fill.symbol' masked cross-symbol contamination by labelling the
    trade with whichever symbol happened to be the exit leg.  That fallback
    is removed; both legs must agree on base_symbol by construction.
    """
    # Both legs are the same symbol — use exit fill's symbol (most recent contract code).
    base        = entry.fill.base_symbol   # group's known base symbol
    mult        = _multiplier(base)
    ep, xp      = entry.price, exit_fill.price
    direction   = "LONG" if entry.side == "BUY" else "SHORT"
    pnl_points  = (xp - ep) if direction == "LONG" else (ep - xp)
    pnl_dollars = pnl_points * mult * entry.qty
    duration    = _duration_min(entry.time_str, exit_fill.timestamp)
    return RoundTrip(
        account      = exit_fill.account or entry.fill.account,
        symbol       = exit_fill.symbol  or entry.fill.symbol,
        base_symbol  = base,
        direction    = direction,
        quantity     = entry.qty,
        entry_time   = entry.time_str,
        exit_time    = exit_fill.timestamp,
        entry_price  = ep,
        exit_price   = xp,
        pnl_points   = pnl_points,
        pnl_dollars  = pnl_dollars,
        duration_min = duration,
        entry_note   = entry.fill.note,
        exit_note    = exit_fill.note,
    )


def _duration_min(entry_ts: str, exit_ts: str) -> float:
    """
    Trade duration in minutes between two ISO timestamp strings.

    NOTE: Returns a SIGNED value (negative = inverted trade where exit
    is before entry).  Callers that need to detect corruption should
    check for duration_min < 0.  Do NOT silently abs() this value —
    negative durations are data-integrity signals.
    """
    try:
        e = datetime.datetime.fromisoformat(entry_ts.replace("Z", "+00:00"))
        x = datetime.datetime.fromisoformat(exit_ts.replace("Z", "+00:00"))
        return (x - e).total_seconds() / 60.0   # FIX v2: removed abs()
    except Exception:
        return 0.0


def pair_fills_to_trades(
    fills: List[FillRecord],
) -> Tuple[List[RoundTrip], List[FillRecord]]:
    """
    Stage 4 -- FIFO Position Resynchronizer.

    Rebuilds completed round-trip trades from a clean, sorted fill stream
    using a FIFO queue that mirrors Sierra Chart's internal FIFO engine.

    Fill Classification
    -------------------
    ENTRY    : position 0 -> non-zero (or scale-in, abs increasing same sign)
    EXIT     : position non-zero -> 0 (or scale-out, abs decreasing same sign)
    SCALE-OUT: partial exit -- abs(position) decreasing, same sign
    FLIP     : position crosses zero (sign reversal)

    Returns
    -------
    (trades, unpaired_fills)
    trades         : List[RoundTrip] -- completed round trips
    unpaired_fills : List[FillRecord] -- entries left open at session end
    """
    trades   : List[RoundTrip] = []
    queue    : List[_OpenLeg]  = []
    position : int             = 0

    sorted_fills = sorted(fills, key=lambda f: (f.ts_val, f.position_order))

    for f in sorted_fills:
        if not f.is_valid():
            continue

        qty   = f.quantity
        side  = f.side
        delta = +qty if side == "BUY" else -qty
        new_pos = position + delta

        # ---- FLIP: crosses zero ----------------------------------------
        if position != 0 and new_pos != 0 and (position > 0) != (new_pos > 0):
            while queue:
                op = queue.pop(0)
                trades.append(_make_round_trip(op, f))
            position = 0
            new_contracts = abs(new_pos)
            queue.append(_OpenLeg(fill=f, side=side, qty=new_contracts,
                                  price=f.price, time_str=f.timestamp))
            position = new_pos
            continue

        # ---- EXIT / SCALE-OUT: moving toward zero ----------------------
        if position != 0 and abs(new_pos) < abs(position) and (
            new_pos == 0 or (position > 0) == (new_pos > 0)
        ):
            to_close = abs(position) - abs(new_pos)
            while to_close > 0 and queue:
                op = queue[0]
                if op.qty <= to_close:
                    to_close -= op.qty
                    queue.pop(0)
                    trades.append(_make_round_trip(op, f))
                else:
                    partial = _OpenLeg(fill=op.fill, side=op.side,
                                       qty=to_close, price=op.price,
                                       time_str=op.time_str)
                    op.qty    -= to_close
                    to_close   = 0
                    trades.append(_make_round_trip(partial, f))
            position = new_pos
            continue

        # ---- ENTRY / SCALE-IN: moving away from zero -------------------
        if new_pos != 0 and (position == 0 or abs(new_pos) > abs(position)):
            new_contracts = abs(new_pos) - abs(position)
            queue.append(_OpenLeg(fill=f, side=side, qty=new_contracts,
                                  price=f.price, time_str=f.timestamp))
            position = new_pos
            continue

        # ---- NO-OP (flat -> flat, or unchanged) ------------------------
        position = new_pos

    unpaired = [op.fill for op in queue]
    return trades, unpaired


# ---------------------------------------------------------------------------
# Stage 5: Sequence Integrity Verifier
# ---------------------------------------------------------------------------

def verify_sequence(
    raw_fills    : List[FillRecord],
    clean_fills  : List[FillRecord],
    trades       : List[RoundTrip],
    unpaired     : List[FillRecord],
) -> Tuple[bool, List[str], int]:
    """
    Stage 5 -- Sequence Integrity Verifier.

    Four checks on the cleaned trade sequence:

    1. Position Balance  : Net delta of clean fills == 0 (or unpaired qty).
    2. Direction Flips   : Count sign reversals in clean fill stream (target=0).
    3. Inverted Trades   : Any RoundTrip with exit_time < entry_time (FIX v2).
    4. Pairing Report    : Log counts for trade/unpaired/ghost summary.

    Returns (ok, messages, flip_count).
    """
    messages   : List[str] = []
    ok         : bool      = True

    # Check 1: Position balance
    net = sum(f.quantity if f.side == "BUY" else -f.quantity for f in clean_fills)
    expected_open = sum(f.quantity if f.side == "BUY" else -f.quantity for f in unpaired)
    if net not in (0, expected_open):
        ok = False
        messages.append(f"POSITION IMBALANCE: net_delta={net}, unpaired_qty={expected_open}")
    else:
        messages.append(f"Position balance OK (net={net})")

    # Check 2: Direction flips
    flip_count = 0
    running    = 0
    for f in clean_fills:
        prev    = running
        running += f.quantity if f.side == "BUY" else -f.quantity
        if prev != 0 and running != 0 and (prev > 0) != (running > 0):
            flip_count += 1
    if flip_count > 0:
        ok = False
        messages.append(f"DIRECTION FLIPS DETECTED: {flip_count} flip(s) remain in clean stream")
    else:
        messages.append("Direction sequence OK (0 flips)")

    # Check 3: Inverted trades (FIX v2 — previously hidden by abs() in _duration_min)
    inverted = [
        t for t in trades
        if t.duration_min < 0
    ]
    if inverted:
        ok = False
        inv_detail = "; ".join(
            f"{t.direction} {t.quantity}x entry={t.entry_time[:19]} exit={t.exit_time[:19]} "
            f"dur={t.duration_min:.1f}min"
            for t in inverted
        )
        messages.append(
            f"INVERTED TRADES DETECTED: {len(inverted)} trade(s) have exit_time < entry_time. "
            f"Details: {inv_detail}"
        )
    else:
        messages.append(f"Inverted-trade check OK (0 inverted trades)")

    # Check 4: Pairing report
    messages.append(
        f"Pairing summary: {len(trades)} completed trades | "
        f"{len(unpaired)} unpaired entries | "
        f"{len(raw_fills) - len(clean_fills)} ghost fills removed"
    )
    return ok, messages, flip_count


# ---------------------------------------------------------------------------
# Main Engine
# ---------------------------------------------------------------------------

class GhostFillEngine:
    """
    Ghost Fill Resynchronization Engine (GFRE).

    Processes a list of FillRecord objects through all 5 GFRE stages and
    returns a GFREResult containing clean RoundTrip trades, ghost counts,
    and sequence integrity status.

    Usage
    -----
        engine = GhostFillEngine()
        result = engine.process(fill_records)
        print(result.summary())

    Or using raw dicts from binary_log_parser:
        fills  = GhostFillEngine.from_dicts(raw_dicts)
        result = engine.process(fills)
    """

    def __init__(self, debug: bool = False):
        """
        Initialize the Ghost Fill Resynchronization Engine.

        Parameters
        ----------
        debug : Emit per-fill ghost classification log entries when True.
        """
        self.debug = debug

    @staticmethod
    def from_dicts(raw_dicts: List[Dict]) -> List[FillRecord]:
        """
        Convert raw parser dicts to validated FillRecord objects.

        Fills that fail is_valid() are silently excluded from the returned
        list — but is_valid() itself calls _record_rejected() for every
        bounds violation, so every exclusion is captured in the module-level
        rejected_fills audit list.  Callers can retrieve them via
        get_rejected_fills().
        """
        records: List[FillRecord] = []
        for d in raw_dicts:
            try:
                r = FillRecord.from_dict(d)
                if r.is_valid():
                    records.append(r)
                # is_valid() already called _record_rejected() if bounds failed
            except Exception as exc:
                logger.debug("Skipping malformed fill dict: %s", exc)
        return records

    def process(
        self,
        fills           : List[FillRecord],
        dedup_bucket_ms : int = 250,
    ) -> GFREResult:
        """
        Execute all 5 GFRE stages on the provided fill stream.

        FIX v3 (August 2026) — Per-Symbol FIFO Isolation
        --------------------------------------------------
        Fills are now grouped by `base_symbol` before Stage 4 runs.
        Each symbol receives its own independent `position` counter and
        FIFO `queue` inside `pair_fills_to_trades()`.  This makes it
        structurally impossible for a fill from one instrument to be
        paired against an entry leg from a different instrument:

        OLD (buggy):
          all_fills → Stage1 → Stage3 → Stage4(one shared queue) → Stage5

        NEW (fixed):
          all_fills
            for each base_symbol:
              sym_fills → Stage2(per-sym) → Stage1(per-sym) → Stage3(per-sym)
                        → Stage4(per-sym, independent queue) → Stage5(per-sym)
            aggregate into GFREResult + GFREResult.per_symbol dict

        Stages 2 (bypass detection) and 3 (dedup) are also run per-symbol:
        - Stage 2 per-symbol: an account may tag one instrument's strategy
          fills reliably while trading another instrument without tags;
          computing note_rate globally would incorrectly suppress the ghost
          filter for the well-tagged symbol.
        - Stage 3 per-symbol: dedup keys include (ts_bucket, price, side,
          qty, account, order_id) — a fill from one symbol cannot collide
          with a fill from another; per-symbol dedup is equivalent but
          makes the isolation explicit.

        Parameters
        ----------
        fills           : FillRecord list (unsorted OK).
        dedup_bucket_ms : Dedup time bucket width in ms (default 250).

        Returns
        -------
        GFREResult  (aggregate) with .per_symbol dict (per-symbol breakdown)
        """
        result = GFREResult()
        if not fills:
            result.notes.append("Empty fill stream -- nothing to process.")
            return result

        result.total_raw_fills = len(fills)
        fills_sorted = sorted(fills, key=lambda f: (f.ts_val, f.position_order))

        # ── Group by base_symbol (preserving sort order within each group) ──
        from collections import defaultdict as _dd
        symbol_groups: Dict[str, List[FillRecord]] = _dd(list)
        for f in fills_sorted:
            symbol_groups[f.base_symbol].append(f)

        all_trades   : List[RoundTrip]  = []
        all_unpaired : List[FillRecord] = []

        for base_sym, sym_fills in symbol_groups.items():
            sr = SymbolGFREResult(base_symbol=base_sym, total_fills=len(sym_fills))

            # Stage 2: Adaptive Bypass — per-symbol note rate
            note_rate, bypass = _compute_note_rate(sym_fills)
            sr.note_rate  = note_rate
            sr.bypass_mode = bypass

            # Stage 1: Tag-Validation Filter — per-symbol, using per-symbol bypass
            ghost_fills      : List[FillRecord] = []
            clean_candidates : List[FillRecord] = []
            for f in sym_fills:
                if bypass:
                    f.suggests_ghost = False
                    clean_candidates.append(f)
                else:
                    is_ghost = f.suggests_ghost or classify_fill(f)
                    f.suggests_ghost = is_ghost
                    if is_ghost:
                        ghost_fills.append(f)
                        if self.debug:
                            logger.debug(
                                "GHOST [%s]: %s %s %dx%s @ %s note='%s'",
                                base_sym, f.timestamp, f.side, f.quantity,
                                f.symbol, f.price, f.note,
                            )
                    else:
                        clean_candidates.append(f)

            sr.ghost_fills_dropped = len(ghost_fills)

            # Stage 3: Deduplication — per-symbol
            deduped = _dedup_fills(clean_candidates, bucket_ms=dedup_bucket_ms)
            sr.clean_fills = len(deduped)

            # Stage 4: FIFO Pairing — INDEPENDENT queue for this symbol only.
            # pair_fills_to_trades() starts with position=0 and queue=[] on
            # every call; different base_symbols NEVER share state.
            trades, unpaired = pair_fills_to_trades(deduped)
            sr.trades        = trades
            sr.unpaired_fills = unpaired
            all_trades.extend(trades)
            all_unpaired.extend(unpaired)

            # Stage 5: Integrity Verification — per-symbol
            ok, msgs, flip_count = verify_sequence(
                sym_fills, deduped, trades, unpaired
            )
            sr.integrity_ok     = ok
            sr.integrity_notes  = msgs
            sr.direction_flips  = flip_count

            result.per_symbol[base_sym] = sr

        # ── Aggregate across all symbols ───────────────────────────────────
        result.ghost_fills_dropped = sum(
            sr.ghost_fills_dropped for sr in result.per_symbol.values()
        )
        result.clean_fills     = sum(
            sr.clean_fills for sr in result.per_symbol.values()
        )
        result.trades          = all_trades
        result.unpaired_fills  = all_unpaired
        result.direction_flips = sum(
            sr.direction_flips for sr in result.per_symbol.values()
        )
        result.integrity_ok    = all(
            sr.integrity_ok for sr in result.per_symbol.values()
        )
        result.bypass_mode     = any(
            sr.bypass_mode for sr in result.per_symbol.values()
        )

        # Summary notes
        syms_str = ", ".join(sorted(result.per_symbol.keys()))
        result.notes.append(
            "Symbols processed: [{}]".format(syms_str)
        )
        for base_sym, sr in sorted(result.per_symbol.items()):
            status     = "PASS" if sr.integrity_ok else "FAIL"
            bypass_tag = " [BYPASS]" if sr.bypass_mode else ""
            result.notes.append(
                "  {}: {} fills | {} ghosts | {} clean | {} trades | "
                "integrity={}{} | note_rate={:.0%}".format(
                    base_sym, sr.total_fills, sr.ghost_fills_dropped,
                    sr.clean_fills, len(sr.trades),
                    status, bypass_tag, sr.note_rate,
                )
            )
        result.notes.append(
            "Totals: {} raw | {} ghosts | {} clean | {} trades | "
            "integrity={}".format(
                result.total_raw_fills, result.ghost_fills_dropped,
                result.clean_fills, len(result.trades),
                "PASS" if result.integrity_ok else "FAIL",
            )
        )

        return result


# ---------------------------------------------------------------------------
# One-Call Convenience Wrapper
# ---------------------------------------------------------------------------

def resync(raw_dicts: List[Dict], debug: bool = False) -> GFREResult:
    """
    One-call convenience: raw fill dicts -> GFREResult.

    Converts raw parser dicts to FillRecords and runs all 5 GFRE stages.

    Example
    -------
        from trading_platform.services.ghost_fill_engine import resync
        from trading_platform.services.binary_log_parser import _parse_file_nitro

        raw, _ = _parse_file_nitro("dataset/TradeActivityLog_2026-06-10_UTC.TM_7.data")
        result = resync(raw)
        print(result.summary())
        for t in result.trades:
            print(t)
    """
    engine = GhostFillEngine(debug=debug)
    fills  = GhostFillEngine.from_dicts(raw_dicts)
    return engine.process(fills)
