"""Initial database schema with foreign keys

Revision ID: 2869930a34db
Revises: 
Create Date: 2025-07-18 14:31:44.470749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2869930a34db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('first_trade_date', sa.DateTime(), nullable=True),
    sa.Column('last_trade_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('data_import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('import_status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_log_file_path', 'data_import_log', ['file_path'], unique=False)
    op.create_index('idx_import_log_start_time', 'data_import_log', ['start_time'], unique=False)
    op.create_index('idx_import_log_status', 'data_import_log', ['import_status'], unique=False)
    op.create_table('sierra_chart_fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('trans_date_time', sa.DateTime(), nullable=False),
    sa.Column('service_order_id', sa.String(length=100), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('trade_account', sa.String(length=50), nullable=False),
    sa.Column('buy_sell', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price2', sa.Float(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('order_action_source', sa.String(length=100), nullable=True),
    sa.Column('internal_order_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('open_close', sa.String(length=10), nullable=False),
    sa.Column('parent_internal_order_id', sa.String(length=100), nullable=True),
    sa.Column('position_quantity', sa.Integer(), nullable=False),
    sa.Column('fill_execution_service_id', sa.String(length=100), nullable=True),
    sa.Column('high_during_position', sa.Float(), nullable=True),
    sa.Column('low_during_position', sa.Float(), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('time_in_force', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('is_automated', sa.String(length=1), nullable=True),
    sa.Column('file_source', sa.String(length=500), nullable=False),
    sa.Column('import_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_order_id', 'internal_order_id', name='uq_sierra_fills_order_ids')
    )
    op.create_index('idx_sierra_fills_account_symbol', 'sierra_chart_fills', ['trade_account', 'symbol'], unique=False)
    op.create_index('idx_sierra_fills_datetime', 'sierra_chart_fills', ['date_time'], unique=False)
    op.create_index('idx_sierra_fills_position_qty', 'sierra_chart_fills', ['position_quantity'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_component_time', 'system_health', ['component', 'check_timestamp'], unique=False)
    op.create_index('idx_health_status', 'system_health', ['status'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('average_win', sa.Float(), nullable=False),
    sa.Column('average_loss', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('largest_win', sa.Float(), nullable=False),
    sa.Column('largest_loss', sa.Float(), nullable=False),
    sa.Column('calculation_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_name'], ['accounts.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_metrics_account_period', 'performance_metrics', ['account_name', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_perf_metrics_symbol', 'performance_metrics', ['symbol'], unique=False)
    op.create_table('processed_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=200), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('entry_order_id', sa.String(length=100), nullable=False),
    sa.Column('exit_order_id', sa.String(length=100), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_name'], ['accounts.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index('idx_processed_trades_account_time', 'processed_trades', ['account_name', 'entry_time'], unique=False)
    op.create_index('idx_processed_trades_pnl', 'processed_trades', ['profit_loss'], unique=False)
    op.create_index('idx_processed_trades_symbol', 'processed_trades', ['symbol'], unique=False)
    op.create_index('idx_processed_trades_temporal', 'processed_trades', ['hour_of_day', 'day_of_week'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('expected_risk', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('historical_win_rate', sa.Float(), nullable=True),
    sa.Column('avg_profit_this_time', sa.Float(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_name'], ['accounts.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_account', 'recommendations', ['account_name'], unique=False)
    op.create_index('idx_recommendations_action', 'recommendations', ['recommended_action'], unique=False)
    op.create_index('idx_recommendations_confidence', 'recommendations', ['confidence_score'], unique=False)
    op.create_index('idx_recommendations_timestamp', 'recommendations', ['timestamp'], unique=False)
    op.create_table('temporal_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('average_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('calculation_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_name'], ['accounts.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_temporal_perf_day', 'temporal_performance', ['day_of_week'], unique=False)
    op.create_index('idx_temporal_perf_hour', 'temporal_performance', ['hour_of_day'], unique=False)
    op.create_index('idx_temporal_perf_lookup', 'temporal_performance', ['account_name', 'symbol', 'hour_of_day', 'day_of_week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_temporal_perf_lookup', table_name='temporal_performance')
    op.drop_index('idx_temporal_perf_hour', table_name='temporal_performance')
    op.drop_index('idx_temporal_perf_day', table_name='temporal_performance')
    op.drop_table('temporal_performance')
    op.drop_index('idx_recommendations_timestamp', table_name='recommendations')
    op.drop_index('idx_recommendations_confidence', table_name='recommendations')
    op.drop_index('idx_recommendations_action', table_name='recommendations')
    op.drop_index('idx_recommendations_account', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_processed_trades_temporal', table_name='processed_trades')
    op.drop_index('idx_processed_trades_symbol', table_name='processed_trades')
    op.drop_index('idx_processed_trades_pnl', table_name='processed_trades')
    op.drop_index('idx_processed_trades_account_time', table_name='processed_trades')
    op.drop_table('processed_trades')
    op.drop_index('idx_perf_metrics_symbol', table_name='performance_metrics')
    op.drop_index('idx_perf_metrics_account_period', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('idx_health_status', table_name='system_health')
    op.drop_index('idx_health_component_time', table_name='system_health')
    op.drop_table('system_health')
    op.drop_index('idx_sierra_fills_position_qty', table_name='sierra_chart_fills')
    op.drop_index('idx_sierra_fills_datetime', table_name='sierra_chart_fills')
    op.drop_index('idx_sierra_fills_account_symbol', table_name='sierra_chart_fills')
    op.drop_table('sierra_chart_fills')
    op.drop_index('idx_import_log_status', table_name='data_import_log')
    op.drop_index('idx_import_log_start_time', table_name='data_import_log')
    op.drop_index('idx_import_log_file_path', table_name='data_import_log')
    op.drop_table('data_import_log')
    op.drop_table('accounts')
    # ### end Alembic commands ###
