"""
TimeBinMonitoringService for real-time trading performance tracking and anomaly detection.

This module provides comprehensive real-time monitoring capabilities for time-bin trading strategies
including performance tracking, anomaly detection, statistical significance monitoring, and market
condition change notifications.

Requirements: 8.1, 8.2, 8.3
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple, Callable, Set
from dataclasses import dataclass, field
from enum import Enum
from collections import deque, defaultdict
import numpy as np
import pandas as pd
from sqlalchemy.orm import Session
from threading import Lock, Event
import statistics

from ..time_bin_analyzer import TimeBinAnalyzer, TimeBin, SimpleTrade
from ..performance_metrics_calculator import PerformanceMetricsCalculator
from ..market_data.vix_data_analyzer import VIXDataAnalyzer
from ..market_data.benchmark_correlation_analyzer import BenchmarkCorrelationAnalyzer
from ...database.connection import get_db_session

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class MonitoringStatus(Enum):
    """Monitoring service status."""
    STOPPED = "stopped"
    STARTING = "starting"
    RUNNING = "running"
    PAUSED = "paused"
    ERROR = "error"


class AnomalyType(Enum):
    """Types of anomalies detected."""
    PERFORMANCE_DEGRADATION = "performance_degradation"
    UNUSUAL_LOSS_STREAK = "unusual_loss_streak"
    VOLUME_ANOMALY = "volume_anomaly"
    TIMING_ANOMALY = "timing_anomaly"
    STATISTICAL_SIGNIFICANCE_LOSS = "statistical_significance_loss"
    MARKET_CORRELATION_CHANGE = "market_correlation_change"
    DRAWDOWN_THRESHOLD_BREACH = "drawdown_threshold_breach"


@dataclass
class MonitoringAlert:
    """Alert generated by the monitoring system."""
    
    alert_id: str
    timestamp: datetime
    time_bin: TimeBin
    alert_type: AnomalyType
    severity: AlertSeverity
    message: str
    data: Dict[str, Any]
    is_acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    auto_resolved: bool = False
    resolution_timestamp: Optional[datetime] = None


@dataclass
class PerformanceSnapshot:
    """Snapshot of time-bin performance at a specific time."""
    
    timestamp: datetime
    time_bin: TimeBin
    trades_count: int
    total_pnl: float
    win_rate: float
    avg_trade_pnl: float
    max_drawdown: float
    sharpe_ratio: float
    profit_factor: float
    recent_trades: List[SimpleTrade]
    statistical_significance: bool
    p_value: float
    market_correlation: Dict[str, float] = field(default_factory=dict)


@dataclass
class MonitoringConfiguration:
    """Configuration for time-bin monitoring."""
    
    # Performance thresholds
    min_win_rate_threshold: float = 0.45
    max_drawdown_threshold: float = 0.15
    min_sharpe_ratio: float = 0.5
    min_profit_factor: float = 1.1
    
    # Statistical thresholds
    significance_threshold: float = 0.05
    min_trades_for_significance: int = 30
    
    # Anomaly detection parameters
    performance_lookback_window: int = 50  # trades
    unusual_streak_threshold: int = 5  # consecutive losses
    volume_anomaly_multiplier: float = 3.0
    timing_anomaly_threshold_minutes: int = 30
    
    # Market correlation thresholds
    correlation_change_threshold: float = 0.2
    vix_regime_change_threshold: float = 5.0
    
    # Monitoring intervals
    check_interval_seconds: int = 30
    alert_cooldown_minutes: int = 15
    
    # Alert settings
    enable_email_alerts: bool = False
    enable_push_notifications: bool = True
    max_alerts_per_hour: int = 10
    
    # Data retention
    snapshot_retention_hours: int = 168  # 1 week
    alert_retention_days: int = 30


class TimeBinMonitoringService:
    """
    Real-time monitoring service for time-bin trading performance.
    
    Provides continuous monitoring of trading performance with anomaly detection,
    statistical significance tracking, and market condition notifications.
    """
    
    def __init__(self, db_session: Optional[Session] = None):
        """Initialize the monitoring service."""
        self.db_session = db_session or get_db_session()
        
        # Core services
        self.time_bin_analyzer = TimeBinAnalyzer(self.db_session)
        self.performance_calculator = PerformanceMetricsCalculator(self.db_session)
        self.vix_analyzer = VIXDataAnalyzer(self.db_session)
        self.benchmark_analyzer = BenchmarkCorrelationAnalyzer(self.db_session)
        
        # Monitoring state
        self.status = MonitoringStatus.STOPPED
        self.monitored_time_bins: Set[TimeBin] = set()
        self.configurations: Dict[TimeBin, MonitoringConfiguration] = {}
        
        # Data storage
        self.performance_snapshots: Dict[TimeBin, deque] = defaultdict(lambda: deque(maxlen=1000))
        self.active_alerts: Dict[str, MonitoringAlert] = {}
        self.alert_history: deque = deque(maxlen=10000)
        
        # Alert management
        self.alert_cooldowns: Dict[Tuple[TimeBin, AnomalyType], datetime] = {}
        self.alert_counters: Dict[datetime, int] = defaultdict(int)
        
        # Threading and async
        self.monitoring_task: Optional[asyncio.Task] = None
        self.stop_event = Event()
        self.data_lock = Lock()
        
        # Callbacks
        self.alert_callbacks: List[Callable[[MonitoringAlert], None]] = []
        self.performance_callbacks: List[Callable[[PerformanceSnapshot], None]] = []
        
        logger.info("TimeBinMonitoringService initialized")
    
    def add_time_bin_monitoring(
        self,
        time_bin: TimeBin,
        config: Optional[MonitoringConfiguration] = None
    ) -> bool:
        """Add a time-bin for monitoring."""
        try:
            with self.data_lock:
                self.monitored_time_bins.add(time_bin)
                self.configurations[time_bin] = config or MonitoringConfiguration()
                
                # Initialize data structures
                if time_bin not in self.performance_snapshots:
                    self.performance_snapshots[time_bin] = deque(maxlen=1000)
                
                logger.info(f"Added monitoring for time-bin {time_bin.account_name}:{time_bin.hour}:{time_bin.minute_bin:02d}")
                return True
                
        except Exception as e:
            logger.error(f"Failed to add time-bin monitoring: {str(e)}")
            return False
    
    def remove_time_bin_monitoring(self, time_bin: TimeBin) -> bool:
        """Remove a time-bin from monitoring."""
        try:
            with self.data_lock:
                if time_bin in self.monitored_time_bins:
                    self.monitored_time_bins.remove(time_bin)
                    
                    # Clean up data structures
                    if time_bin in self.configurations:
                        del self.configurations[time_bin]
                    if time_bin in self.performance_snapshots:
                        del self.performance_snapshots[time_bin]
                    
                    # Remove related alerts
                    alerts_to_remove = [
                        alert_id for alert_id, alert in self.active_alerts.items()
                        if alert.time_bin == time_bin
                    ]
                    for alert_id in alerts_to_remove:
                        del self.active_alerts[alert_id]
                    
                    logger.info(f"Removed monitoring for time-bin {time_bin.account_name}:{time_bin.hour}:{time_bin.minute_bin:02d}")
                    return True
                return False
                
        except Exception as e:
            logger.error(f"Failed to remove time-bin monitoring: {str(e)}")
            return False
    
    async def start_monitoring(self) -> bool:
        """Start the monitoring service."""
        try:
            if self.status == MonitoringStatus.RUNNING:
                logger.warning("Monitoring service is already running")
                return True
            
            self.status = MonitoringStatus.STARTING
            self.stop_event.clear()
            
            # Start monitoring task
            self.monitoring_task = asyncio.create_task(self._monitoring_loop())
            
            self.status = MonitoringStatus.RUNNING
            logger.info("TimeBinMonitoringService started successfully")
            return True
            
        except Exception as e:
            self.status = MonitoringStatus.ERROR
            logger.error(f"Failed to start monitoring service: {str(e)}")
            return False
    
    async def stop_monitoring(self) -> bool:
        """Stop the monitoring service."""
        try:
            if self.status == MonitoringStatus.STOPPED:
                return True
            
            self.stop_event.set()
            
            if self.monitoring_task:
                self.monitoring_task.cancel()
                try:
                    await self.monitoring_task
                except asyncio.CancelledError:
                    pass
                self.monitoring_task = None
            
            self.status = MonitoringStatus.STOPPED
            logger.info("TimeBinMonitoringService stopped")
            return True
            
        except Exception as e:
            logger.error(f"Failed to stop monitoring service: {str(e)}")
            return False
    
    async def _monitoring_loop(self):
        """Main monitoring loop."""
        logger.info("Starting monitoring loop")
        
        while not self.stop_event.is_set():
            try:
                # Check each monitored time-bin
                with self.data_lock:
                    time_bins_to_check = list(self.monitored_time_bins)
                
                for time_bin in time_bins_to_check:
                    try:
                        await self._check_time_bin(time_bin)
                    except Exception as e:
                        logger.error(f"Error checking time-bin {time_bin}: {str(e)}")
                
                # Clean up old data
                await self._cleanup_old_data()
                
                # Wait for next check
                config = next(iter(self.configurations.values()), MonitoringConfiguration())
                await asyncio.sleep(config.check_interval_seconds)
                
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Error in monitoring loop: {str(e)}")
                await asyncio.sleep(5)  # Brief pause before retrying
        
        logger.info("Monitoring loop stopped")
    
    async def _check_time_bin(self, time_bin: TimeBin):
        """Check a specific time-bin for anomalies and updates."""
        config = self.configurations.get(time_bin, MonitoringConfiguration())
        
        try:
            # Get current performance snapshot
            snapshot = await self._create_performance_snapshot(time_bin)
            
            if snapshot:
                # Store snapshot
                with self.data_lock:
                    self.performance_snapshots[time_bin].append(snapshot)
                
                # Check for anomalies
                anomalies = await self._detect_anomalies(time_bin, snapshot, config)
                
                # Generate alerts for detected anomalies
                for anomaly_type, anomaly_data in anomalies:
                    await self._generate_alert(time_bin, anomaly_type, anomaly_data, config)
                
                # Notify callbacks
                for callback in self.performance_callbacks:
                    try:
                        callback(snapshot)
                    except Exception as e:
                        logger.error(f"Error in performance callback: {str(e)}")
        
        except Exception as e:
            logger.error(f"Error checking time-bin {time_bin}: {str(e)}")
    
    async def _create_performance_snapshot(self, time_bin: TimeBin) -> Optional[PerformanceSnapshot]:
        """Create a performance snapshot for a time-bin."""
        try:
            # Get recent trades
            end_time = datetime.now()
            start_time = end_time - timedelta(hours=24)  # Last 24 hours
            
            trades = self.time_bin_analyzer.get_time_bin_trades(
                time_bin,
                start_date=start_time.date(),
                end_date=end_time.date()
            )
            
            if not trades:
                return None
            
            # Calculate performance metrics
            performance_data = self.performance_calculator.calculate_comprehensive_metrics(trades)
            
            # Get recent trades for detailed analysis
            recent_trades = sorted(trades, key=lambda t: t.exit_time, reverse=True)[:50]
            
            # Calculate statistical significance
            returns = [trade.profit_loss for trade in trades]
            p_value = self._calculate_significance_test(returns)
            statistical_significance = p_value < 0.05
            
            # Get market correlation
            market_correlation = {}
            try:
                spy_corr = self.benchmark_analyzer.calculate_correlation_with_benchmark(
                    time_bin.account_name, time_bin.hour, time_bin.minute_bin, "SPY"
                )
                qqq_corr = self.benchmark_analyzer.calculate_correlation_with_benchmark(
                    time_bin.account_name, time_bin.hour, time_bin.minute_bin, "QQQ"
                )
                vix_corr_data = self.vix_analyzer.calculate_vix_correlation(
                    time_bin.account_name, time_bin.hour, time_bin.minute_bin
                )
                
                market_correlation = {
                    "SPY": spy_corr,
                    "QQQ": qqq_corr,
                    "VIX": vix_corr_data.get("overall_correlation", 0.0)
                }
            except Exception as e:
                logger.warning(f"Failed to get market correlation data: {str(e)}")
            
            snapshot = PerformanceSnapshot(
                timestamp=datetime.now(),
                time_bin=time_bin,
                trades_count=len(trades),
                total_pnl=performance_data.get("total_pnl", 0.0),
                win_rate=performance_data.get("win_rate", 0.0),
                avg_trade_pnl=performance_data.get("avg_trade_pnl", 0.0),
                max_drawdown=performance_data.get("max_drawdown", 0.0),
                sharpe_ratio=performance_data.get("sharpe_ratio", 0.0),
                profit_factor=performance_data.get("profit_factor", 0.0),
                recent_trades=recent_trades,
                statistical_significance=statistical_significance,
                p_value=p_value,
                market_correlation=market_correlation
            )
            
            return snapshot
            
        except Exception as e:
            logger.error(f"Failed to create performance snapshot: {str(e)}")
            return None
    
    def _calculate_significance_test(self, returns: List[float]) -> float:
        """Calculate statistical significance of returns using t-test."""
        if len(returns) < 10:
            return 1.0  # Not enough data
        
        try:
            from scipy import stats
            # One-sample t-test against zero mean
            t_statistic, p_value = stats.ttest_1samp(returns, 0)
            return p_value
        except ImportError:
            # Fallback to simple calculation if scipy not available
            if len(returns) < 2:
                return 1.0
            
            mean = statistics.mean(returns)
            std_dev = statistics.stdev(returns)
            
            if std_dev == 0:
                return 0.0 if mean != 0 else 1.0
            
            # Simple t-test approximation
            t_stat = mean / (std_dev / (len(returns) ** 0.5))
            # Rough p-value approximation
            p_value = max(0.001, min(1.0, 2 * (1 - abs(t_stat) / 5)))
            return p_value
    
    async def _detect_anomalies(
        self,
        time_bin: TimeBin,
        current_snapshot: PerformanceSnapshot,
        config: MonitoringConfiguration
    ) -> List[Tuple[AnomalyType, Dict[str, Any]]]:
        """Detect anomalies in the current performance snapshot."""
        anomalies = []
        
        try:
            # Get historical snapshots for comparison
            with self.data_lock:
                historical_snapshots = list(self.performance_snapshots[time_bin])
            
            if len(historical_snapshots) < 10:
                return anomalies  # Not enough historical data
            
            # 1. Performance degradation detection
            if await self._detect_performance_degradation(current_snapshot, historical_snapshots, config):
                anomalies.append((AnomalyType.PERFORMANCE_DEGRADATION, {
                    "current_win_rate": current_snapshot.win_rate,
                    "threshold": config.min_win_rate_threshold,
                    "current_sharpe": current_snapshot.sharpe_ratio,
                    "min_sharpe": config.min_sharpe_ratio
                }))
            
            # 2. Unusual loss streak detection
            if await self._detect_loss_streak(current_snapshot, config):
                consecutive_losses = self._count_consecutive_losses(current_snapshot.recent_trades)
                anomalies.append((AnomalyType.UNUSUAL_LOSS_STREAK, {
                    "consecutive_losses": consecutive_losses,
                    "threshold": config.unusual_streak_threshold
                }))
            
            # 3. Volume anomaly detection
            if await self._detect_volume_anomaly(current_snapshot, historical_snapshots, config):
                historical_avg_trades = np.mean([s.trades_count for s in historical_snapshots[-20:]])
                anomalies.append((AnomalyType.VOLUME_ANOMALY, {
                    "current_trades": current_snapshot.trades_count,
                    "historical_average": historical_avg_trades,
                    "multiplier": config.volume_anomaly_multiplier
                }))
            
            # 4. Statistical significance loss
            if (not current_snapshot.statistical_significance and 
                current_snapshot.trades_count >= config.min_trades_for_significance):
                anomalies.append((AnomalyType.STATISTICAL_SIGNIFICANCE_LOSS, {
                    "p_value": current_snapshot.p_value,
                    "threshold": config.significance_threshold,
                    "trades_count": current_snapshot.trades_count
                }))
            
            # 5. Market correlation change
            correlation_changes = await self._detect_correlation_changes(
                current_snapshot, historical_snapshots, config
            )
            if correlation_changes:
                anomalies.append((AnomalyType.MARKET_CORRELATION_CHANGE, correlation_changes))
            
            # 6. Drawdown threshold breach
            if abs(current_snapshot.max_drawdown) > config.max_drawdown_threshold:
                anomalies.append((AnomalyType.DRAWDOWN_THRESHOLD_BREACH, {
                    "current_drawdown": current_snapshot.max_drawdown,
                    "threshold": config.max_drawdown_threshold
                }))
            
            return anomalies
            
        except Exception as e:
            logger.error(f"Error detecting anomalies: {str(e)}")
            return []
    
    async def _detect_performance_degradation(
        self,
        current: PerformanceSnapshot,
        historical: List[PerformanceSnapshot],
        config: MonitoringConfiguration
    ) -> bool:
        """Detect significant performance degradation."""
        try:
            # Check if current performance is below thresholds
            if (current.win_rate < config.min_win_rate_threshold or
                current.sharpe_ratio < config.min_sharpe_ratio or
                current.profit_factor < config.min_profit_factor):
                
                # Compare with recent historical performance
                recent_snapshots = historical[-10:] if len(historical) >= 10 else historical
                if recent_snapshots:
                    avg_historical_win_rate = np.mean([s.win_rate for s in recent_snapshots])
                    avg_historical_sharpe = np.mean([s.sharpe_ratio for s in recent_snapshots])
                    
                    # Significant degradation if current is much worse than historical
                    if (current.win_rate < avg_historical_win_rate - 0.1 or
                        current.sharpe_ratio < avg_historical_sharpe - 0.5):
                        return True
                
                return True  # Below absolute thresholds
            
            return False
            
        except Exception as e:
            logger.error(f"Error detecting performance degradation: {str(e)}")
            return False
    
    async def _detect_loss_streak(self, snapshot: PerformanceSnapshot, config: MonitoringConfiguration) -> bool:
        """Detect unusual consecutive loss streaks."""
        try:
            consecutive_losses = self._count_consecutive_losses(snapshot.recent_trades)
            return consecutive_losses >= config.unusual_streak_threshold
            
        except Exception as e:
            logger.error(f"Error detecting loss streak: {str(e)}")
            return False
    
    def _count_consecutive_losses(self, trades: List[SimpleTrade]) -> int:
        """Count consecutive losing trades from the most recent."""
        consecutive_losses = 0
        
        for trade in trades:  # Assumes trades are sorted by exit_time desc
            if trade.profit_loss < 0:
                consecutive_losses += 1
            else:
                break
        
        return consecutive_losses
    
    async def _detect_volume_anomaly(
        self,
        current: PerformanceSnapshot,
        historical: List[PerformanceSnapshot],
        config: MonitoringConfiguration
    ) -> bool:
        """Detect unusual trading volume."""
        try:
            if len(historical) < 5:
                return False
            
            historical_trades_counts = [s.trades_count for s in historical[-20:]]
            avg_trades = np.mean(historical_trades_counts)
            std_trades = np.std(historical_trades_counts)
            
            if std_trades == 0:
                return False
            
            # Anomaly if current volume is significantly different
            z_score = abs(current.trades_count - avg_trades) / std_trades
            return z_score > config.volume_anomaly_multiplier
            
        except Exception as e:
            logger.error(f"Error detecting volume anomaly: {str(e)}")
            return False
    
    async def _detect_correlation_changes(
        self,
        current: PerformanceSnapshot,
        historical: List[PerformanceSnapshot],
        config: MonitoringConfiguration
    ) -> Optional[Dict[str, Any]]:
        """Detect significant changes in market correlations."""
        try:
            if len(historical) < 10 or not current.market_correlation:
                return None
            
            # Get recent historical correlations
            recent_snapshots = [s for s in historical[-10:] if s.market_correlation]
            if not recent_snapshots:
                return None
            
            changes = {}
            for symbol in current.market_correlation:
                current_corr = current.market_correlation[symbol]
                historical_corrs = [
                    s.market_correlation.get(symbol, 0) 
                    for s in recent_snapshots
                    if symbol in s.market_correlation
                ]
                
                if historical_corrs:
                    avg_historical_corr = np.mean(historical_corrs)
                    change = abs(current_corr - avg_historical_corr)
                    
                    if change > config.correlation_change_threshold:
                        changes[symbol] = {
                            "current": current_corr,
                            "historical_avg": avg_historical_corr,
                            "change": change
                        }
            
            return changes if changes else None
            
        except Exception as e:
            logger.error(f"Error detecting correlation changes: {str(e)}")
            return None
    
    async def _generate_alert(
        self,
        time_bin: TimeBin,
        anomaly_type: AnomalyType,
        anomaly_data: Dict[str, Any],
        config: MonitoringConfiguration
    ):
        """Generate an alert for a detected anomaly."""
        try:
            # Check cooldown period
            cooldown_key = (time_bin, anomaly_type)
            if cooldown_key in self.alert_cooldowns:
                if datetime.now() < self.alert_cooldowns[cooldown_key]:
                    return  # Still in cooldown
            
            # Check rate limiting
            current_hour = datetime.now().replace(minute=0, second=0, microsecond=0)
            if self.alert_counters[current_hour] >= config.max_alerts_per_hour:
                return  # Rate limit exceeded
            
            # Determine severity
            severity = self._determine_alert_severity(anomaly_type, anomaly_data)
            
            # Generate alert message
            message = self._generate_alert_message(time_bin, anomaly_type, anomaly_data, severity)
            
            # Create alert
            alert = MonitoringAlert(
                alert_id=f"alert_{int(datetime.now().timestamp())}_{anomaly_type.value}",
                timestamp=datetime.now(),
                time_bin=time_bin,
                alert_type=anomaly_type,
                severity=severity,
                message=message,
                data=anomaly_data
            )
            
            # Store alert
            with self.data_lock:
                self.active_alerts[alert.alert_id] = alert
                self.alert_history.append(alert)
            
            # Set cooldown
            self.alert_cooldowns[cooldown_key] = datetime.now() + timedelta(minutes=config.alert_cooldown_minutes)
            
            # Update rate limiting
            self.alert_counters[current_hour] += 1
            
            # Notify callbacks
            for callback in self.alert_callbacks:
                try:
                    callback(alert)
                except Exception as e:
                    logger.error(f"Error in alert callback: {str(e)}")
            
            logger.warning(f"Generated {severity.value} alert: {message}")
            
        except Exception as e:
            logger.error(f"Error generating alert: {str(e)}")
    
    def _determine_alert_severity(self, anomaly_type: AnomalyType, data: Dict[str, Any]) -> AlertSeverity:
        """Determine the severity of an alert based on anomaly type and data."""
        if anomaly_type == AnomalyType.DRAWDOWN_THRESHOLD_BREACH:
            drawdown = abs(data.get("current_drawdown", 0))
            if drawdown > 0.25:
                return AlertSeverity.EMERGENCY
            elif drawdown > 0.20:
                return AlertSeverity.CRITICAL
            else:
                return AlertSeverity.WARNING
        
        elif anomaly_type == AnomalyType.PERFORMANCE_DEGRADATION:
            win_rate = data.get("current_win_rate", 0.5)
            if win_rate < 0.3:
                return AlertSeverity.CRITICAL
            elif win_rate < 0.4:
                return AlertSeverity.WARNING
            else:
                return AlertSeverity.INFO
        
        elif anomaly_type == AnomalyType.UNUSUAL_LOSS_STREAK:
            streak = data.get("consecutive_losses", 0)
            if streak >= 10:
                return AlertSeverity.CRITICAL
            elif streak >= 7:
                return AlertSeverity.WARNING
            else:
                return AlertSeverity.INFO
        
        elif anomaly_type == AnomalyType.STATISTICAL_SIGNIFICANCE_LOSS:
            p_value = data.get("p_value", 1.0)
            if p_value > 0.2:
                return AlertSeverity.WARNING
            else:
                return AlertSeverity.INFO
        
        else:
            return AlertSeverity.INFO
    
    def _generate_alert_message(
        self,
        time_bin: TimeBin,
        anomaly_type: AnomalyType,
        data: Dict[str, Any],
        severity: AlertSeverity
    ) -> str:
        """Generate a human-readable alert message."""
        time_bin_str = f"{time_bin.account_name}:{time_bin.hour}:{time_bin.minute_bin:02d}"
        
        if anomaly_type == AnomalyType.PERFORMANCE_DEGRADATION:
            return (f"{severity.value.upper()}: Performance degradation detected for {time_bin_str}. "
                   f"Win rate: {data.get('current_win_rate', 0):.1%}, "
                   f"Sharpe ratio: {data.get('current_sharpe', 0):.2f}")
        
        elif anomaly_type == AnomalyType.UNUSUAL_LOSS_STREAK:
            return (f"{severity.value.upper()}: Unusual loss streak for {time_bin_str}. "
                   f"{data.get('consecutive_losses', 0)} consecutive losses detected")
        
        elif anomaly_type == AnomalyType.DRAWDOWN_THRESHOLD_BREACH:
            return (f"{severity.value.upper()}: Drawdown threshold breached for {time_bin_str}. "
                   f"Current drawdown: {abs(data.get('current_drawdown', 0)):.1%}")
        
        elif anomaly_type == AnomalyType.STATISTICAL_SIGNIFICANCE_LOSS:
            return (f"{severity.value.upper()}: Statistical significance lost for {time_bin_str}. "
                   f"P-value: {data.get('p_value', 1.0):.3f} with {data.get('trades_count', 0)} trades")
        
        elif anomaly_type == AnomalyType.VOLUME_ANOMALY:
            return (f"{severity.value.upper()}: Trading volume anomaly for {time_bin_str}. "
                   f"Current: {data.get('current_trades', 0)}, "
                   f"Historical avg: {data.get('historical_average', 0):.1f}")
        
        elif anomaly_type == AnomalyType.MARKET_CORRELATION_CHANGE:
            symbols_changed = list(data.keys())
            return (f"{severity.value.upper()}: Market correlation change for {time_bin_str}. "
                   f"Symbols affected: {', '.join(symbols_changed)}")
        
        else:
            return f"{severity.value.upper()}: {anomaly_type.value} detected for {time_bin_str}"
    
    async def _cleanup_old_data(self):
        """Clean up old snapshots and expired alerts."""
        try:
            current_time = datetime.now()
            
            # Clean up old snapshots
            with self.data_lock:
                for time_bin, snapshots in self.performance_snapshots.items():
                    config = self.configurations.get(time_bin, MonitoringConfiguration())
                    cutoff_time = current_time - timedelta(hours=config.snapshot_retention_hours)
                    
                    # Remove old snapshots
                    while snapshots and snapshots[0].timestamp < cutoff_time:
                        snapshots.popleft()
                
                # Clean up old alerts
                alerts_to_remove = []
                for alert_id, alert in self.active_alerts.items():
                    config = self.configurations.get(alert.time_bin, MonitoringConfiguration())
                    if current_time - alert.timestamp > timedelta(days=config.alert_retention_days):
                        alerts_to_remove.append(alert_id)
                
                for alert_id in alerts_to_remove:
                    del self.active_alerts[alert_id]
                
                # Clean up rate limiting counters
                old_hours = [
                    hour for hour in self.alert_counters
                    if current_time - hour > timedelta(hours=24)
                ]
                for hour in old_hours:
                    del self.alert_counters[hour]
                
                # Clean up alert cooldowns
                expired_cooldowns = [
                    key for key, expiry in self.alert_cooldowns.items()
                    if current_time > expiry
                ]
                for key in expired_cooldowns:
                    del self.alert_cooldowns[key]
            
        except Exception as e:
            logger.error(f"Error cleaning up old data: {str(e)}")
    
    # Public interface methods
    
    def add_alert_callback(self, callback: Callable[[MonitoringAlert], None]):
        """Add a callback function to be called when alerts are generated."""
        self.alert_callbacks.append(callback)
    
    def add_performance_callback(self, callback: Callable[[PerformanceSnapshot], None]):
        """Add a callback function to be called when performance snapshots are created."""
        self.performance_callbacks.append(callback)
    
    def get_active_alerts(self, time_bin: Optional[TimeBin] = None) -> List[MonitoringAlert]:
        """Get currently active alerts."""
        with self.data_lock:
            if time_bin:
                return [alert for alert in self.active_alerts.values() if alert.time_bin == time_bin]
            else:
                return list(self.active_alerts.values())
    
    def get_performance_history(self, time_bin: TimeBin, hours: int = 24) -> List[PerformanceSnapshot]:
        """Get performance history for a time-bin."""
        cutoff_time = datetime.now() - timedelta(hours=hours)
        
        with self.data_lock:
            snapshots = self.performance_snapshots.get(time_bin, deque())
            return [s for s in snapshots if s.timestamp >= cutoff_time]
    
    def acknowledge_alert(self, alert_id: str, acknowledged_by: str = "system") -> bool:
        """Acknowledge an active alert."""
        try:
            with self.data_lock:
                if alert_id in self.active_alerts:
                    alert = self.active_alerts[alert_id]
                    alert.is_acknowledged = True
                    alert.acknowledged_at = datetime.now()
                    alert.acknowledged_by = acknowledged_by
                    return True
                return False
                
        except Exception as e:
            logger.error(f"Error acknowledging alert: {str(e)}")
            return False
    
    def get_monitoring_status(self) -> Dict[str, Any]:
        """Get the current status of the monitoring service."""
        with self.data_lock:
            return {
                "status": self.status.value,
                "monitored_time_bins": len(self.monitored_time_bins),
                "active_alerts": len(self.active_alerts),
                "total_snapshots": sum(len(snapshots) for snapshots in self.performance_snapshots.values()),
                "alert_history_size": len(self.alert_history),
                "uptime_seconds": 0 if not hasattr(self, '_start_time') else (datetime.now() - self._start_time).total_seconds()
            }
    
    def __del__(self):
        """Cleanup when service is destroyed."""
        if self.status == MonitoringStatus.RUNNING:
            self.stop_event.set()